### ISSUE TITLE
Incorrect License

### ISSUE THREAD

**Issue by ghost** [suburbanpuma/nnsvs-spanish-support#1]
Thank you for taking it upon yourself to continue support for Spanish.

Friendly reminder that each project had it's own license and the one for the romance language support is at https://github.com/DYVAUX/nnsvs-romance-language-support/blob/main/LICENSE.md

It will be much less restrictive to use the current CC-BY license. While still requiring attribution and a link to our work/license, you may use your own _compatible_ license with any parts that are solely yours.
Compatible examples include GPLv2, GPLv3, MIT, and most other CC licenses.
You can read more here: https://creativecommons.org/licenses/by/4.0/legalcode#s3a

If you use components of additional DYVAUX projects, you will need to link those works as well as ensuring compatibility with the separate licenses.

Thank you.

**Comment by suburbanpuma** [comment]
I have changed the license,

**Comment by suburbanpuma** [comment]
I have changed the license to the romance adjacent one. It _should_ be correct now, but please notify of any other mistakes I may have made, as I am not very good at using GitHub.
